// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRdPlb7S2SU55rEdYfEBqzOsYwcvWtIY',
    appId: '1:592423508864:web:03dfe483792b9992887f65',
    messagingSenderId: '592423508864',
    projectId: 'pdf-maker-4259c',
    authDomain: 'pdf-maker-4259c.firebaseapp.com',
    storageBucket: 'pdf-maker-4259c.firebasestorage.app',
    measurementId: 'G-CZXDP2MNSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yxacGb616WlHQhNtgS98s4FzjlQSsVE',
    appId: '1:592423508864:android:2d5e9c6afa6b3c3e887f65',
    messagingSenderId: '592423508864',
    projectId: 'pdf-maker-4259c',
    storageBucket: 'pdf-maker-4259c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFCoEOniPn39VKjJsymUsqWB4SdZlGc0',
    appId: '1:592423508864:ios:3c0ea7b4c519d85b887f65',
    messagingSenderId: '592423508864',
    projectId: 'pdf-maker-4259c',
    storageBucket: 'pdf-maker-4259c.firebasestorage.app',
    iosBundleId: 'com.pdfmaker.pdfconvert.imagetopdf.readpdfapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJFCoEOniPn39VKjJsymUsqWB4SdZlGc0',
    appId: '1:592423508864:ios:978eb920c890a8f1887f65',
    messagingSenderId: '592423508864',
    projectId: 'pdf-maker-4259c',
    storageBucket: 'pdf-maker-4259c.firebasestorage.app',
    iosBundleId: 'com.example.smallPdfMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRdPlb7S2SU55rEdYfEBqzOsYwcvWtIY',
    appId: '1:592423508864:web:e53d34f811ab011a887f65',
    messagingSenderId: '592423508864',
    projectId: 'pdf-maker-4259c',
    authDomain: 'pdf-maker-4259c.firebaseapp.com',
    storageBucket: 'pdf-maker-4259c.firebasestorage.app',
    measurementId: 'G-7GV5EWRL6C',
  );
}
